[build]
  command = "npm run build"
  publish = "client/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_FLAGS = "--legacy-peer-deps"
  REACT_APP_ENV = "production"

[functions]
  external_node_modules = ["mongodb"]
  node_bundler = "esbuild"

# WebSocket support
[[redirects]]
  from = "/socket.io/*"
  to = "/.netlify/functions/chat"
  status = 200
  force = true
  [redirects.headers]
    Connection = "Upgrade"
    Upgrade = "websocket"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "client/build"

[context.production.environment]
  REACT_APP_ENV = "production"
  CI = "false"

[context.staging.environment]
  REACT_APP_ENV = "staging"
  CI = "false" 